### ISSUE TITLE
Error: Cannot find module 'js-yaml'

### ISSUE THREAD

**Issue by dahoo** [brickify/stl-exporter#4]
I got an error while executing. Seems like you missed a dependency.

```
Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/daniel/.nvm/versions/node/v5.5.0/lib/node_modules/stl-exporter/build/cli.js:9:10)
    at Object.<anonymous> (/home/daniel/.nvm/versions/node/v5.5.0/lib/node_modules/stl-exporter/build/cli.js:51:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by Steditor** [comment]
Looks like the dependency currently is only listed as dev dependency: https://github.com/brickify/stl-exporter/blob/master/package.json#L25
